config/routes.rb
Rails.application.routes.draw do
  root to: "restaurants#index"
  resources :restaurants, only:[:index, :show, :new, :create] do
    resources :reviews, only:[:create, :new]
  end

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/models/restaurant.rb
class Restaurant < ApplicationRecord
has_many :reviews, dependent: :destroy

validates :name, :address, :category, presence: true
validates :category, inclusion: { in: ["chinese", "italian", "japanese", "french", "belgian"] }
end

app/models/review.rb
class Review < ApplicationRecord
  belongs_to :restaurant

  validates :content, :rating, presence: true
  validates :rating, numericality: { only_integer: true, greater_than_or_equal_to: 0, less_than_or_equal_to: 5}
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
  before_action :set_restaurant, only: [:show]

  def index
    @restaurants = Restaurant.all
  end

  def show
  end

  def new
    @restaurant = Restaurant.new
  end

  def create
    @restaurant = Restaurant.new(restaurant_params)

    if @restaurant.save
      redirect_to @restaurant, notice: 'Restaurant was successfully created.'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:id])
  end

  def restaurant_params
    params.require(:restaurant).permit(:name, :address, :category)
  end
end

app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
  before_action :set_restaurant

  def new
    @restaurant = Restaurant.find(params[:restaurant_id])
    @review = Review.new
  end

  def create
    @review = @restaurant.reviews.new(review_params)

    if @review.save
      redirect_to @restaurant, notice: 'Review was successfully created.'
    else
      render :new
    end
  end

  private

  def set_restaurant
    @restaurant = Restaurant.find(params[:restaurant_id])
  end

  def review_params
    params.require(:review).permit(:content, :rating)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/restaurants_helper.rb
module RestaurantsHelper
end

app/helpers/resturant_helper.rb
module ResturantHelper
end

app/helpers/reviews_helper.rb
module ReviewsHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.1.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-1BmE4kWBq78iYhFldvKuhfTAU6auU8tT94WrHftjDbrCEXSU1oBoqyl2QvZ6jIW3" crossorigin="anonymous">
    <title>RailsYelpMvp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/restaurants/_form.html.erb
<%= simple_form_for(@restaurants) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :name %>
    <%= f.input :address %>
    <%= f.input :phone_number %>
    <%= f.input :category %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/restaurants/index.html.erb
<p style="color: green"><%= notice %></p>
<h1>Restaurants</h1>
<div id="restaurants">
  <% @restaurants.each do |restaurant| %>
    <p>
    <strong>Name:</strong>
    <%= restaurant.name %>
  </p>
  <p>
    <strong>Address:</strong>
    <%= restaurant.address %>
  </p>
    <p>
      <%= link_to "Show this restaurant", restaurant_path(restaurant) %>
    </p>
  <% end %>
</div>
<%= link_to "New restaurant", new_restaurant_path %>

app/views/restaurants/new.html.erb
<div class="container">
  <div class="row">
    <div class="col-xs-12 col-sm-10 col-sm-offset-1">
      <h1> Create a new Restaurant </h2>
      <%= simple_form_for(@restaurant) do |f| %>
          <%= f.input :name %>
          <%= f.input :address %>
          <%= f.input :phone_number %>
          <%= f.input :category, collection: %w( chinese italian japanese french belgian) %>
          <%= f.submit class: 'btn btn-primary' %>
        <% end %>
    </div>
  </div>
</div>

app/views/restaurants/review.html.erb
<h1>hello</h1>

app/views/restaurants/show.html.erb
<div>
<p style="color: green"><%= notice %></p>
<h1><%= @restaurants.name %></h1>
<p><%= @restaurants.address %></p>
<p><%= @restaurants.phone_number %></p>
<p><%= @restaurants.category %></p>
</div>

app/views/reviews/new.html.erb
<h1>hello</h1>